<?php

/**
 * Implements hook_commerce_cart_attributes_refresh_alter
 */
function hc_package_types_commerce_cart_attributes_refresh_alter(&$commands, $form, $form_state) {

  $product = $form_state['default_product'];
  
  // only call this hook for TEAM PACKAGE products
  $type = $product->type;
  if ($type != 'team_package') {
    return;
  }
  
  /* Check if this newly chosen product is associated with a specific PACKAGE TYPE (field_package_type) */
  $fields = entity_metadata_wrapper('commerce_product', $product);
  $package_type = $fields->field_package_type->value();
  
  /* Package type = a taxonomy term object, so define a new wrapper for getting the info */
  $term = entity_metadata_wrapper('taxonomy_term', $package_type);
  $widget = $term->field_widget->value();

  /* Depending on the widget itself (currently hardcoded), some extra actions are needed: show/hide fields */
  switch ($widget) {
    case 'fixed_dates':
      $output = "Here a list of selectable dates of group sessions will be shown";
      break;
    case 'filled_in_calendar':
      $output = "Here a partially filled in calendar will be shown";
      break;
    case 'blank_calendar':
      $output = "Here a blank calendar will be shown";
      break;
  }


  /* Execute commands */
  $commands[] = ajax_command_alert("Some action needs to be done.");
}