<?php

/**
 * Implements hook_menu
 */
function hc_calendar_menu() {
  $items = array();
  
  $items['calendar'] = array(
    'title' => t('Calendar'),
    'page callback' => 'hc_calendar_calendar_page',
    'access arguments' => array('access content'),
  );
  
  return $items;
}


/**
 * Implements hook_views_api
 */
function hc_calendar_views_api() {
  return array(
    'api' => 3, 
  );
}



/**
 * The aorta function: render the calendar page
 */
function hc_calendar_calendar_page() {

  $output = views_embed_view('calendar', 'default');
  
  return $output;

  $user_location = $_SESSION['user_location'];
}